/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package openxr.templates

import org.lwjgl.generator.*
import openxr.*

val ANDROID_trackables_marker = "ANDROIDTrackablesMarker".nativeClassXR("ANDROID_trackables_marker", type = "instance", postfix = "ANDROID") {
    IntConstant(
        "ANDROID_trackables_marker_SPEC_VERSION".."1"
    )

    StringConstant(
        "ANDROID_TRACKABLES_MARKER_EXTENSION_NAME".."XR_ANDROID_trackables_marker"
    )

    EnumConstant(
        "TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_ANDROID".."1000707000",
        "TYPE_TRACKABLE_MARKER_CONFIGURATION_ANDROID".."1000707001",
        "TYPE_TRACKABLE_MARKER_ANDROID".."1000707002"
    )

    EnumConstant(
        "TRACKABLE_TYPE_MARKER_ANDROID".."1000707000"
    )

    EnumConstant(
        "TRACKABLE_MARKER_TRACKING_MODE_DYNAMIC_ANDROID".."0",
        "TRACKABLE_MARKER_TRACKING_MODE_STATIC_ANDROID".."1"
    )

    EnumConstant(
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_4X4_50_ANDROID".."0",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_4X4_100_ANDROID".."1",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_4X4_250_ANDROID".."2",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_4X4_1000_ANDROID".."3",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_5X5_50_ANDROID".."4",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_5X5_100_ANDROID".."5",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_5X5_250_ANDROID".."6",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_5X5_1000_ANDROID".."7",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_6X6_50_ANDROID".."8",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_6X6_100_ANDROID".."9",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_6X6_250_ANDROID".."10",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_6X6_1000_ANDROID".."11",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_7X7_50_ANDROID".."12",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_7X7_100_ANDROID".."13",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_7X7_250_ANDROID".."14",
        "TRACKABLE_MARKER_DICTIONARY_ARUCO_7X7_1000_ANDROID".."15",
        "TRACKABLE_MARKER_DICTIONARY_APRILTAG_16H5_ANDROID".."16",
        "TRACKABLE_MARKER_DICTIONARY_APRILTAG_25H9_ANDROID".."17",
        "TRACKABLE_MARKER_DICTIONARY_APRILTAG_36H10_ANDROID".."18",
        "TRACKABLE_MARKER_DICTIONARY_APRILTAG_36H11_ANDROID".."19"
    )

    XrResult(
        "GetTrackableMarkerANDROID",

        XrTrackableTrackerANDROID("tracker"),
        XrTrackableGetInfoANDROID.const.p("getInfo"),
        XrTrackableMarkerANDROID.p("markerOutput")
    )
}