/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package openxr.templates

import org.lwjgl.generator.*
import openxr.*

val ANDROID_face_tracking = "ANDROIDFaceTracking".nativeClassXR("ANDROID_face_tracking", type = "instance", postfix = "ANDROID") {
    IntConstant(
        "ANDROID_face_tracking_SPEC_VERSION".."1"
    )

    StringConstant(
        "ANDROID_FACE_TRACKING_EXTENSION_NAME".."XR_ANDROID_face_tracking"
    )

    EnumConstant(
        "TYPE_FACE_TRACKER_CREATE_INFO_ANDROID".."1000458000",
        "TYPE_FACE_STATE_GET_INFO_ANDROID".."1000458001",
        "TYPE_FACE_STATE_ANDROID".."1000458002",
        "TYPE_SYSTEM_FACE_TRACKING_PROPERTIES_ANDROID".."1000458003"
    )

    EnumConstant(
        "ERROR_SERVICE_NOT_READY_ANDROID".."-1000458000"
    )

    EnumConstant(
        "OBJECT_TYPE_FACE_TRACKER_ANDROID".."1000458000"
    )

    EnumConstant(
        "FACE_PARAMETER_COUNT_ANDROID".."68"
    )

    EnumConstant(
        "FACE_REGION_CONFIDENCE_COUNT_ANDROID".."3"
    )

    EnumConstant(
        "FACE_PARAMETER_INDICES_BROW_LOWERER_L_ANDROID".."0",
        "FACE_PARAMETER_INDICES_BROW_LOWERER_R_ANDROID".."1",
        "FACE_PARAMETER_INDICES_CHEEK_PUFF_L_ANDROID".."2",
        "FACE_PARAMETER_INDICES_CHEEK_PUFF_R_ANDROID".."3",
        "FACE_PARAMETER_INDICES_CHEEK_RAISER_L_ANDROID".."4",
        "FACE_PARAMETER_INDICES_CHEEK_RAISER_R_ANDROID".."5",
        "FACE_PARAMETER_INDICES_CHEEK_SUCK_L_ANDROID".."6",
        "FACE_PARAMETER_INDICES_CHEEK_SUCK_R_ANDROID".."7",
        "FACE_PARAMETER_INDICES_CHIN_RAISER_B_ANDROID".."8",
        "FACE_PARAMETER_INDICES_CHIN_RAISER_T_ANDROID".."9",
        "FACE_PARAMETER_INDICES_DIMPLER_L_ANDROID".."10",
        "FACE_PARAMETER_INDICES_DIMPLER_R_ANDROID".."11",
        "FACE_PARAMETER_INDICES_EYES_CLOSED_L_ANDROID".."12",
        "FACE_PARAMETER_INDICES_EYES_CLOSED_R_ANDROID".."13",
        "FACE_PARAMETER_INDICES_EYES_LOOK_DOWN_L_ANDROID".."14",
        "FACE_PARAMETER_INDICES_EYES_LOOK_DOWN_R_ANDROID".."15",
        "FACE_PARAMETER_INDICES_EYES_LOOK_LEFT_L_ANDROID".."16",
        "FACE_PARAMETER_INDICES_EYES_LOOK_LEFT_R_ANDROID".."17",
        "FACE_PARAMETER_INDICES_EYES_LOOK_RIGHT_L_ANDROID".."18",
        "FACE_PARAMETER_INDICES_EYES_LOOK_RIGHT_R_ANDROID".."19",
        "FACE_PARAMETER_INDICES_EYES_LOOK_UP_L_ANDROID".."20",
        "FACE_PARAMETER_INDICES_EYES_LOOK_UP_R_ANDROID".."21",
        "FACE_PARAMETER_INDICES_INNER_BROW_RAISER_L_ANDROID".."22",
        "FACE_PARAMETER_INDICES_INNER_BROW_RAISER_R_ANDROID".."23",
        "FACE_PARAMETER_INDICES_JAW_DROP_ANDROID".."24",
        "FACE_PARAMETER_INDICES_JAW_SIDEWAYS_LEFT_ANDROID".."25",
        "FACE_PARAMETER_INDICES_JAW_SIDEWAYS_RIGHT_ANDROID".."26",
        "FACE_PARAMETER_INDICES_JAW_THRUST_ANDROID".."27",
        "FACE_PARAMETER_INDICES_LID_TIGHTENER_L_ANDROID".."28",
        "FACE_PARAMETER_INDICES_LID_TIGHTENER_R_ANDROID".."29",
        "FACE_PARAMETER_INDICES_LIP_CORNER_DEPRESSOR_L_ANDROID".."30",
        "FACE_PARAMETER_INDICES_LIP_CORNER_DEPRESSOR_R_ANDROID".."31",
        "FACE_PARAMETER_INDICES_LIP_CORNER_PULLER_L_ANDROID".."32",
        "FACE_PARAMETER_INDICES_LIP_CORNER_PULLER_R_ANDROID".."33",
        "FACE_PARAMETER_INDICES_LIP_FUNNELER_LB_ANDROID".."34",
        "FACE_PARAMETER_INDICES_LIP_FUNNELER_LT_ANDROID".."35",
        "FACE_PARAMETER_INDICES_LIP_FUNNELER_RB_ANDROID".."36",
        "FACE_PARAMETER_INDICES_LIP_FUNNELER_RT_ANDROID".."37",
        "FACE_PARAMETER_INDICES_LIP_PRESSOR_L_ANDROID".."38",
        "FACE_PARAMETER_INDICES_LIP_PRESSOR_R_ANDROID".."39",
        "FACE_PARAMETER_INDICES_LIP_PUCKER_L_ANDROID".."40",
        "FACE_PARAMETER_INDICES_LIP_PUCKER_R_ANDROID".."41",
        "FACE_PARAMETER_INDICES_LIP_STRETCHER_L_ANDROID".."42",
        "FACE_PARAMETER_INDICES_LIP_STRETCHER_R_ANDROID".."43",
        "FACE_PARAMETER_INDICES_LIP_SUCK_LB_ANDROID".."44",
        "FACE_PARAMETER_INDICES_LIP_SUCK_LT_ANDROID".."45",
        "FACE_PARAMETER_INDICES_LIP_SUCK_RB_ANDROID".."46",
        "FACE_PARAMETER_INDICES_LIP_SUCK_RT_ANDROID".."47",
        "FACE_PARAMETER_INDICES_LIP_TIGHTENER_L_ANDROID".."48",
        "FACE_PARAMETER_INDICES_LIP_TIGHTENER_R_ANDROID".."49",
        "FACE_PARAMETER_INDICES_LIPS_TOWARD_ANDROID".."50",
        "FACE_PARAMETER_INDICES_LOWER_LIP_DEPRESSOR_L_ANDROID".."51",
        "FACE_PARAMETER_INDICES_LOWER_LIP_DEPRESSOR_R_ANDROID".."52",
        "FACE_PARAMETER_INDICES_MOUTH_LEFT_ANDROID".."53",
        "FACE_PARAMETER_INDICES_MOUTH_RIGHT_ANDROID".."54",
        "FACE_PARAMETER_INDICES_NOSE_WRINKLER_L_ANDROID".."55",
        "FACE_PARAMETER_INDICES_NOSE_WRINKLER_R_ANDROID".."56",
        "FACE_PARAMETER_INDICES_OUTER_BROW_RAISER_L_ANDROID".."57",
        "FACE_PARAMETER_INDICES_OUTER_BROW_RAISER_R_ANDROID".."58",
        "FACE_PARAMETER_INDICES_UPPER_LID_RAISER_L_ANDROID".."59",
        "FACE_PARAMETER_INDICES_UPPER_LID_RAISER_R_ANDROID".."60",
        "FACE_PARAMETER_INDICES_UPPER_LIP_RAISER_L_ANDROID".."61",
        "FACE_PARAMETER_INDICES_UPPER_LIP_RAISER_R_ANDROID".."62",
        "FACE_PARAMETER_INDICES_TONGUE_OUT_ANDROID".."63",
        "FACE_PARAMETER_INDICES_TONGUE_LEFT_ANDROID".."64",
        "FACE_PARAMETER_INDICES_TONGUE_RIGHT_ANDROID".."65",
        "FACE_PARAMETER_INDICES_TONGUE_UP_ANDROID".."66",
        "FACE_PARAMETER_INDICES_TONGUE_DOWN_ANDROID".."67"
    )

    EnumConstant(
        "FACE_TRACKING_STATE_PAUSED_ANDROID".."0",
        "FACE_TRACKING_STATE_STOPPED_ANDROID".."1",
        "FACE_TRACKING_STATE_TRACKING_ANDROID".."2"
    )

    EnumConstant(
        "FACE_CONFIDENCE_REGIONS_LOWER_ANDROID".."0",
        "FACE_CONFIDENCE_REGIONS_LEFT_UPPER_ANDROID".."1",
        "FACE_CONFIDENCE_REGIONS_RIGHT_UPPER_ANDROID".."2"
    )

    XrResult(
        "CreateFaceTrackerANDROID",

        XrSession("session"),
        XrFaceTrackerCreateInfoANDROID.const.p("createInfo"),
        Check(1)..XrFaceTrackerANDROID.p("faceTracker")
    )

    XrResult(
        "DestroyFaceTrackerANDROID",

        XrFaceTrackerANDROID("faceTracker")
    )

    XrResult(
        "GetFaceStateANDROID",

        XrFaceTrackerANDROID("faceTracker"),
        XrFaceStateGetInfoANDROID.const.p("getInfo"),
        XrFaceStateANDROID.p("faceStateOutput")
    )

    XrResult(
        "GetFaceCalibrationStateANDROID",

        XrFaceTrackerANDROID("faceTracker"),
        Check(1)..XrBool32.p("faceIsCalibratedOutput")
    )
}