/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package openxr.templates

import org.lwjgl.generator.*
import openxr.*

val EXT_spatial_marker_tracking = "EXTSpatialMarkerTracking".nativeClassXR("EXT_spatial_marker_tracking", type = "instance", postfix = "EXT") {
    IntConstant(
        "EXT_spatial_marker_tracking_SPEC_VERSION".."1"
    )

    StringConstant(
        "EXT_SPATIAL_MARKER_TRACKING_EXTENSION_NAME".."XR_EXT_spatial_marker_tracking"
    )

    EnumConstant(
        "SPATIAL_CAPABILITY_MARKER_TRACKING_QR_CODE_EXT".."1000743000",
        "SPATIAL_CAPABILITY_MARKER_TRACKING_MICRO_QR_CODE_EXT".."1000743001",
        "SPATIAL_CAPABILITY_MARKER_TRACKING_ARUCO_MARKER_EXT".."1000743002",
        "SPATIAL_CAPABILITY_MARKER_TRACKING_APRIL_TAG_EXT".."1000743003"
    )

    EnumConstant(
        "SPATIAL_COMPONENT_TYPE_MARKER_EXT".."1000743000"
    )

    EnumConstant(
        "SPATIAL_CAPABILITY_FEATURE_MARKER_TRACKING_FIXED_SIZE_MARKERS_EXT".."1000743000",
        "SPATIAL_CAPABILITY_FEATURE_MARKER_TRACKING_STATIC_MARKERS_EXT".."1000743001"
    )

    EnumConstant(
        "TYPE_SPATIAL_CAPABILITY_CONFIGURATION_QR_CODE_EXT".."1000743000",
        "TYPE_SPATIAL_CAPABILITY_CONFIGURATION_MICRO_QR_CODE_EXT".."1000743001",
        "TYPE_SPATIAL_CAPABILITY_CONFIGURATION_ARUCO_MARKER_EXT".."1000743002",
        "TYPE_SPATIAL_CAPABILITY_CONFIGURATION_APRIL_TAG_EXT".."1000743003",
        "TYPE_SPATIAL_MARKER_SIZE_EXT".."1000743004",
        "TYPE_SPATIAL_MARKER_STATIC_OPTIMIZATION_EXT".."1000743005",
        "TYPE_SPATIAL_COMPONENT_MARKER_LIST_EXT".."1000743006"
    )

    EnumConstant(
        "SPATIAL_MARKER_ARUCO_DICT_4X4_50_EXT".."1",
        "SPATIAL_MARKER_ARUCO_DICT_4X4_100_EXT".."2",
        "SPATIAL_MARKER_ARUCO_DICT_4X4_250_EXT".."3",
        "SPATIAL_MARKER_ARUCO_DICT_4X4_1000_EXT".."4",
        "SPATIAL_MARKER_ARUCO_DICT_5X5_50_EXT".."5",
        "SPATIAL_MARKER_ARUCO_DICT_5X5_100_EXT".."6",
        "SPATIAL_MARKER_ARUCO_DICT_5X5_250_EXT".."7",
        "SPATIAL_MARKER_ARUCO_DICT_5X5_1000_EXT".."8",
        "SPATIAL_MARKER_ARUCO_DICT_6X6_50_EXT".."9",
        "SPATIAL_MARKER_ARUCO_DICT_6X6_100_EXT".."10",
        "SPATIAL_MARKER_ARUCO_DICT_6X6_250_EXT".."11",
        "SPATIAL_MARKER_ARUCO_DICT_6X6_1000_EXT".."12",
        "SPATIAL_MARKER_ARUCO_DICT_7X7_50_EXT".."13",
        "SPATIAL_MARKER_ARUCO_DICT_7X7_100_EXT".."14",
        "SPATIAL_MARKER_ARUCO_DICT_7X7_250_EXT".."15",
        "SPATIAL_MARKER_ARUCO_DICT_7X7_1000_EXT".."16"
    )

    EnumConstant(
        "SPATIAL_MARKER_APRIL_TAG_DICT_16H5_EXT".."1",
        "SPATIAL_MARKER_APRIL_TAG_DICT_25H9_EXT".."2",
        "SPATIAL_MARKER_APRIL_TAG_DICT_36H10_EXT".."3",
        "SPATIAL_MARKER_APRIL_TAG_DICT_36H11_EXT".."4"
    )
}