/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package openxr.templates

import org.lwjgl.generator.*
import openxr.*

val META_body_tracking_full_body = "METABodyTrackingFullBody".nativeClassXR("META_body_tracking_full_body", type = "instance", postfix = "META") {
    IntConstant(
        "META_body_tracking_full_body_SPEC_VERSION".."1"
    )

    StringConstant(
        "META_BODY_TRACKING_FULL_BODY_EXTENSION_NAME".."XR_META_body_tracking_full_body"
    )

    EnumConstant(
        "TYPE_SYSTEM_PROPERTIES_BODY_TRACKING_FULL_BODY_META".."1000274000"
    )

    EnumConstant(
        "BODY_JOINT_SET_FULL_BODY_META".."1000274000"
    )

    EnumConstant(
        "FULL_BODY_JOINT_ROOT_META".."0",
        "FULL_BODY_JOINT_HIPS_META".."1",
        "FULL_BODY_JOINT_SPINE_LOWER_META".."2",
        "FULL_BODY_JOINT_SPINE_MIDDLE_META".."3",
        "FULL_BODY_JOINT_SPINE_UPPER_META".."4",
        "FULL_BODY_JOINT_CHEST_META".."5",
        "FULL_BODY_JOINT_NECK_META".."6",
        "FULL_BODY_JOINT_HEAD_META".."7",
        "FULL_BODY_JOINT_LEFT_SHOULDER_META".."8",
        "FULL_BODY_JOINT_LEFT_SCAPULA_META".."9",
        "FULL_BODY_JOINT_LEFT_ARM_UPPER_META".."10",
        "FULL_BODY_JOINT_LEFT_ARM_LOWER_META".."11",
        "FULL_BODY_JOINT_LEFT_HAND_WRIST_TWIST_META".."12",
        "FULL_BODY_JOINT_RIGHT_SHOULDER_META".."13",
        "FULL_BODY_JOINT_RIGHT_SCAPULA_META".."14",
        "FULL_BODY_JOINT_RIGHT_ARM_UPPER_META".."15",
        "FULL_BODY_JOINT_RIGHT_ARM_LOWER_META".."16",
        "FULL_BODY_JOINT_RIGHT_HAND_WRIST_TWIST_META".."17",
        "FULL_BODY_JOINT_LEFT_HAND_PALM_META".."18",
        "FULL_BODY_JOINT_LEFT_HAND_WRIST_META".."19",
        "FULL_BODY_JOINT_LEFT_HAND_THUMB_METACARPAL_META".."20",
        "FULL_BODY_JOINT_LEFT_HAND_THUMB_PROXIMAL_META".."21",
        "FULL_BODY_JOINT_LEFT_HAND_THUMB_DISTAL_META".."22",
        "FULL_BODY_JOINT_LEFT_HAND_THUMB_TIP_META".."23",
        "FULL_BODY_JOINT_LEFT_HAND_INDEX_METACARPAL_META".."24",
        "FULL_BODY_JOINT_LEFT_HAND_INDEX_PROXIMAL_META".."25",
        "FULL_BODY_JOINT_LEFT_HAND_INDEX_INTERMEDIATE_META".."26",
        "FULL_BODY_JOINT_LEFT_HAND_INDEX_DISTAL_META".."27",
        "FULL_BODY_JOINT_LEFT_HAND_INDEX_TIP_META".."28",
        "FULL_BODY_JOINT_LEFT_HAND_MIDDLE_METACARPAL_META".."29",
        "FULL_BODY_JOINT_LEFT_HAND_MIDDLE_PROXIMAL_META".."30",
        "FULL_BODY_JOINT_LEFT_HAND_MIDDLE_INTERMEDIATE_META".."31",
        "FULL_BODY_JOINT_LEFT_HAND_MIDDLE_DISTAL_META".."32",
        "FULL_BODY_JOINT_LEFT_HAND_MIDDLE_TIP_META".."33",
        "FULL_BODY_JOINT_LEFT_HAND_RING_METACARPAL_META".."34",
        "FULL_BODY_JOINT_LEFT_HAND_RING_PROXIMAL_META".."35",
        "FULL_BODY_JOINT_LEFT_HAND_RING_INTERMEDIATE_META".."36",
        "FULL_BODY_JOINT_LEFT_HAND_RING_DISTAL_META".."37",
        "FULL_BODY_JOINT_LEFT_HAND_RING_TIP_META".."38",
        "FULL_BODY_JOINT_LEFT_HAND_LITTLE_METACARPAL_META".."39",
        "FULL_BODY_JOINT_LEFT_HAND_LITTLE_PROXIMAL_META".."40",
        "FULL_BODY_JOINT_LEFT_HAND_LITTLE_INTERMEDIATE_META".."41",
        "FULL_BODY_JOINT_LEFT_HAND_LITTLE_DISTAL_META".."42",
        "FULL_BODY_JOINT_LEFT_HAND_LITTLE_TIP_META".."43",
        "FULL_BODY_JOINT_RIGHT_HAND_PALM_META".."44",
        "FULL_BODY_JOINT_RIGHT_HAND_WRIST_META".."45",
        "FULL_BODY_JOINT_RIGHT_HAND_THUMB_METACARPAL_META".."46",
        "FULL_BODY_JOINT_RIGHT_HAND_THUMB_PROXIMAL_META".."47",
        "FULL_BODY_JOINT_RIGHT_HAND_THUMB_DISTAL_META".."48",
        "FULL_BODY_JOINT_RIGHT_HAND_THUMB_TIP_META".."49",
        "FULL_BODY_JOINT_RIGHT_HAND_INDEX_METACARPAL_META".."50",
        "FULL_BODY_JOINT_RIGHT_HAND_INDEX_PROXIMAL_META".."51",
        "FULL_BODY_JOINT_RIGHT_HAND_INDEX_INTERMEDIATE_META".."52",
        "FULL_BODY_JOINT_RIGHT_HAND_INDEX_DISTAL_META".."53",
        "FULL_BODY_JOINT_RIGHT_HAND_INDEX_TIP_META".."54",
        "FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_METACARPAL_META".."55",
        "FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_PROXIMAL_META".."56",
        "FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_INTERMEDIATE_META".."57",
        "FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_DISTAL_META".."58",
        "FULL_BODY_JOINT_RIGHT_HAND_MIDDLE_TIP_META".."59",
        "FULL_BODY_JOINT_RIGHT_HAND_RING_METACARPAL_META".."60",
        "FULL_BODY_JOINT_RIGHT_HAND_RING_PROXIMAL_META".."61",
        "FULL_BODY_JOINT_RIGHT_HAND_RING_INTERMEDIATE_META".."62",
        "FULL_BODY_JOINT_RIGHT_HAND_RING_DISTAL_META".."63",
        "FULL_BODY_JOINT_RIGHT_HAND_RING_TIP_META".."64",
        "FULL_BODY_JOINT_RIGHT_HAND_LITTLE_METACARPAL_META".."65",
        "FULL_BODY_JOINT_RIGHT_HAND_LITTLE_PROXIMAL_META".."66",
        "FULL_BODY_JOINT_RIGHT_HAND_LITTLE_INTERMEDIATE_META".."67",
        "FULL_BODY_JOINT_RIGHT_HAND_LITTLE_DISTAL_META".."68",
        "FULL_BODY_JOINT_RIGHT_HAND_LITTLE_TIP_META".."69",
        "FULL_BODY_JOINT_LEFT_UPPER_LEG_META".."70",
        "FULL_BODY_JOINT_LEFT_LOWER_LEG_META".."71",
        "FULL_BODY_JOINT_LEFT_FOOT_ANKLE_TWIST_META".."72",
        "FULL_BODY_JOINT_LEFT_FOOT_ANKLE_META".."73",
        "FULL_BODY_JOINT_LEFT_FOOT_SUBTALAR_META".."74",
        "FULL_BODY_JOINT_LEFT_FOOT_TRANSVERSE_META".."75",
        "FULL_BODY_JOINT_LEFT_FOOT_BALL_META".."76",
        "FULL_BODY_JOINT_RIGHT_UPPER_LEG_META".."77",
        "FULL_BODY_JOINT_RIGHT_LOWER_LEG_META".."78",
        "FULL_BODY_JOINT_RIGHT_FOOT_ANKLE_TWIST_META".."79",
        "FULL_BODY_JOINT_RIGHT_FOOT_ANKLE_META".."80",
        "FULL_BODY_JOINT_RIGHT_FOOT_SUBTALAR_META".."81",
        "FULL_BODY_JOINT_RIGHT_FOOT_TRANSVERSE_META".."82",
        "FULL_BODY_JOINT_RIGHT_FOOT_BALL_META".."83",
        "FULL_BODY_JOINT_COUNT_META".."84",
        "FULL_BODY_JOINT_NONE_META".."85"
    )
}