/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package openxr.templates

import org.lwjgl.generator.*
import openxr.*

val ULTRALEAP_hand_tracking_forearm = "ULTRALEAPHandTrackingForearm".nativeClassXR("ULTRALEAP_hand_tracking_forearm", type = "instance", postfix = "ULTRALEAP") {
    IntConstant(
        "ULTRALEAP_hand_tracking_forearm_SPEC_VERSION".."1"
    )

    StringConstant(
        "ULTRALEAP_HAND_TRACKING_FOREARM_EXTENSION_NAME".."XR_ULTRALEAP_hand_tracking_forearm"
    )

    EnumConstant(
        "HAND_JOINT_SET_HAND_WITH_FOREARM_ULTRALEAP".."1000149000"
    )

    EnumConstant(
        "HAND_FOREARM_JOINT_PALM_ULTRALEAP".."0",
        "HAND_FOREARM_JOINT_WRIST_ULTRALEAP".."1",
        "HAND_FOREARM_JOINT_THUMB_METACARPAL_ULTRALEAP".."2",
        "HAND_FOREARM_JOINT_THUMB_PROXIMAL_ULTRALEAP".."3",
        "HAND_FOREARM_JOINT_THUMB_DISTAL_ULTRALEAP".."4",
        "HAND_FOREARM_JOINT_THUMB_TIP_ULTRALEAP".."5",
        "HAND_FOREARM_JOINT_INDEX_METACARPAL_ULTRALEAP".."6",
        "HAND_FOREARM_JOINT_INDEX_PROXIMAL_ULTRALEAP".."7",
        "HAND_FOREARM_JOINT_INDEX_INTERMEDIATE_ULTRALEAP".."8",
        "HAND_FOREARM_JOINT_INDEX_DISTAL_ULTRALEAP".."9",
        "HAND_FOREARM_JOINT_INDEX_TIP_ULTRALEAP".."10",
        "HAND_FOREARM_JOINT_MIDDLE_METACARPAL_ULTRALEAP".."11",
        "HAND_FOREARM_JOINT_MIDDLE_PROXIMAL_ULTRALEAP".."12",
        "HAND_FOREARM_JOINT_MIDDLE_INTERMEDIATE_ULTRALEAP".."13",
        "HAND_FOREARM_JOINT_MIDDLE_DISTAL_ULTRALEAP".."14",
        "HAND_FOREARM_JOINT_MIDDLE_TIP_ULTRALEAP".."15",
        "HAND_FOREARM_JOINT_RING_METACARPAL_ULTRALEAP".."16",
        "HAND_FOREARM_JOINT_RING_PROXIMAL_ULTRALEAP".."17",
        "HAND_FOREARM_JOINT_RING_INTERMEDIATE_ULTRALEAP".."18",
        "HAND_FOREARM_JOINT_RING_DISTAL_ULTRALEAP".."19",
        "HAND_FOREARM_JOINT_RING_TIP_ULTRALEAP".."20",
        "HAND_FOREARM_JOINT_LITTLE_METACARPAL_ULTRALEAP".."21",
        "HAND_FOREARM_JOINT_LITTLE_PROXIMAL_ULTRALEAP".."22",
        "HAND_FOREARM_JOINT_LITTLE_INTERMEDIATE_ULTRALEAP".."23",
        "HAND_FOREARM_JOINT_LITTLE_DISTAL_ULTRALEAP".."24",
        "HAND_FOREARM_JOINT_LITTLE_TIP_ULTRALEAP".."25",
        "HAND_FOREARM_JOINT_ELBOW_ULTRALEAP".."26"
    )
}