/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package vulkan.templates

import org.lwjgl.generator.*
import vulkan.*

val ARM_data_graph_optical_flow = "ARMDataGraphOpticalFlow".nativeClassVK("ARM_data_graph_optical_flow", type = "device", postfix = "ARM") {
    IntConstant(
        "ARM_DATA_GRAPH_OPTICAL_FLOW_SPEC_VERSION".."1"
    )

    StringConstant(
        "ARM_DATA_GRAPH_OPTICAL_FLOW_EXTENSION_NAME".."VK_ARM_data_graph_optical_flow"
    )

    EnumConstant(
        "STRUCTURE_TYPE_PHYSICAL_DEVICE_DATA_GRAPH_OPTICAL_FLOW_FEATURES_ARM".."1000631000",
        "STRUCTURE_TYPE_QUEUE_FAMILY_DATA_GRAPH_OPTICAL_FLOW_PROPERTIES_ARM".."1000631001",
        "STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_OPTICAL_FLOW_CREATE_INFO_ARM".."1000631002",
        "STRUCTURE_TYPE_DATA_GRAPH_OPTICAL_FLOW_IMAGE_FORMAT_INFO_ARM".."1000631003",
        "STRUCTURE_TYPE_DATA_GRAPH_OPTICAL_FLOW_IMAGE_FORMAT_PROPERTIES_ARM".."1000631004",
        "STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_OPTICAL_FLOW_DISPATCH_INFO_ARM".."1000631005",
        "STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_RESOURCE_INFO_IMAGE_LAYOUT_ARM".."1000631006",
        "STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SINGLE_NODE_CREATE_INFO_ARM".."1000631007",
        "STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_SINGLE_NODE_CONNECTION_ARM".."1000631008"
    )

    EnumConstantLong(
        "FORMAT_FEATURE_2_DATA_GRAPH_OPTICAL_FLOW_IMAGE_BIT_ARM".enum(0x100000000000000L),
        "FORMAT_FEATURE_2_DATA_GRAPH_OPTICAL_FLOW_VECTOR_BIT_ARM".enum(0x200000000000000L),
        "FORMAT_FEATURE_2_DATA_GRAPH_OPTICAL_FLOW_COST_BIT_ARM".enum(0x400000000000000L)
    )

    EnumConstant(
        "PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_TYPE_OPTICAL_FLOW_ARM".."1000631000"
    )

    EnumConstant(
        "DATA_GRAPH_PIPELINE_NODE_CONNECTION_TYPE_OPTICAL_FLOW_INPUT_ARM".."1000631000",
        "DATA_GRAPH_PIPELINE_NODE_CONNECTION_TYPE_OPTICAL_FLOW_REFERENCE_ARM".."1000631001",
        "DATA_GRAPH_PIPELINE_NODE_CONNECTION_TYPE_OPTICAL_FLOW_HINT_ARM".."1000631002",
        "DATA_GRAPH_PIPELINE_NODE_CONNECTION_TYPE_OPTICAL_FLOW_FLOW_VECTOR_ARM".."1000631003",
        "DATA_GRAPH_PIPELINE_NODE_CONNECTION_TYPE_OPTICAL_FLOW_COST_ARM".."1000631004"
    )

    EnumConstant(
        "DATA_GRAPH_PIPELINE_NODE_TYPE_OPTICAL_FLOW_ARM".."1000631000"
    )

    EnumConstantLong(
        "DATA_GRAPH_PIPELINE_SESSION_CREATE_OPTICAL_FLOW_CACHE_BIT_ARM".enum(0x00000002L)
    )

    EnumConstant(
        "DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_OPTICAL_FLOW_CACHE_ARM".."1000631001"
    )

    EnumConstant(
        "DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_UNKNOWN_ARM".."0",
        "DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_1X1_BIT_ARM".enum(0x00000001),
        "DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_2X2_BIT_ARM".enum(0x00000002),
        "DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_4X4_BIT_ARM".enum(0x00000004),
        "DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_8X8_BIT_ARM".enum(0x00000008)
    )

    EnumConstant(
        "DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_UNKNOWN_ARM".."0",
        "DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_SLOW_ARM".."1",
        "DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_MEDIUM_ARM".."2",
        "DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_FAST_ARM".."3"
    )

    EnumConstant(
        "DATA_GRAPH_OPTICAL_FLOW_CREATE_ENABLE_HINT_BIT_ARM".enum(0x00000001),
        "DATA_GRAPH_OPTICAL_FLOW_CREATE_ENABLE_COST_BIT_ARM".enum(0x00000002),
        "DATA_GRAPH_OPTICAL_FLOW_CREATE_RESERVED_30_BIT_ARM".enum(0x40000000)
    )

    EnumConstant(
        "DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_UNKNOWN_ARM".."0",
        "DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_INPUT_BIT_ARM".enum(0x00000001),
        "DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_OUTPUT_BIT_ARM".enum(0x00000002),
        "DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_HINT_BIT_ARM".enum(0x00000004),
        "DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_COST_BIT_ARM".enum(0x00000008)
    )

    EnumConstant(
        "DATA_GRAPH_OPTICAL_FLOW_EXECUTE_DISABLE_TEMPORAL_HINTS_BIT_ARM".enum(0x00000001),
        "DATA_GRAPH_OPTICAL_FLOW_EXECUTE_INPUT_UNCHANGED_BIT_ARM".enum(0x00000002),
        "DATA_GRAPH_OPTICAL_FLOW_EXECUTE_REFERENCE_UNCHANGED_BIT_ARM".enum(0x00000004),
        "DATA_GRAPH_OPTICAL_FLOW_EXECUTE_INPUT_IS_PREVIOUS_REFERENCE_BIT_ARM".enum(0x00000008),
        "DATA_GRAPH_OPTICAL_FLOW_EXECUTE_REFERENCE_IS_PREVIOUS_INPUT_BIT_ARM".enum(0x00000010)
    )

    VkResult(
        "GetPhysicalDeviceQueueFamilyDataGraphOpticalFlowImageFormatsARM",

        VkPhysicalDevice("physicalDevice"),
        uint32_t("queueFamilyIndex"),
        VkQueueFamilyDataGraphPropertiesARM.const.p("pQueueFamilyDataGraphProperties"),
        VkDataGraphOpticalFlowImageFormatInfoARM.const.p("pOpticalFlowImageFormatInfo"),
        AutoSize("pImageFormatProperties")..Check(1)..uint32_t.p("pFormatCount"),
        nullable..VkDataGraphOpticalFlowImageFormatPropertiesARM.p("pImageFormatProperties")
    )

    VkResult(
        "GetPhysicalDeviceQueueFamilyDataGraphEngineOperationPropertiesARM",

        VkPhysicalDevice("physicalDevice"),
        uint32_t("queueFamilyIndex"),
        VkQueueFamilyDataGraphPropertiesARM.const.p("pQueueFamilyDataGraphProperties"),
        nullable..VkBaseOutStructure.p("pProperties")
    )
}