/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package vulkan.templates

import org.lwjgl.generator.*
import vulkan.*

val EXT_subpass_merge_feedback = "EXTSubpassMergeFeedback".nativeClassVK("EXT_subpass_merge_feedback", type = "device", postfix = "EXT") {
    IntConstant(
        "EXT_SUBPASS_MERGE_FEEDBACK_SPEC_VERSION".."2"
    )

    StringConstant(
        "EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME".."VK_EXT_subpass_merge_feedback"
    )

    EnumConstant(
        "STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_MERGE_FEEDBACK_FEATURES_EXT".."1000458000",
        "STRUCTURE_TYPE_RENDER_PASS_CREATION_CONTROL_EXT".."1000458001",
        "STRUCTURE_TYPE_RENDER_PASS_CREATION_FEEDBACK_CREATE_INFO_EXT".."1000458002",
        "STRUCTURE_TYPE_RENDER_PASS_SUBPASS_FEEDBACK_CREATE_INFO_EXT".."1000458003"
    )

    EnumConstant(
        "SUBPASS_MERGE_STATUS_MERGED_EXT".."0",
        "SUBPASS_MERGE_STATUS_DISALLOWED_EXT".."1",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_SIDE_EFFECTS_EXT".."2",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_SAMPLES_MISMATCH_EXT".."3",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_VIEWS_MISMATCH_EXT".."4",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_ALIASING_EXT".."5",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_DEPENDENCIES_EXT".."6",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_INCOMPATIBLE_INPUT_ATTACHMENT_EXT".."7",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_TOO_MANY_ATTACHMENTS_EXT".."8",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_INSUFFICIENT_STORAGE_EXT".."9",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_DEPTH_STENCIL_COUNT_EXT".."10",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_RESOLVE_ATTACHMENT_REUSE_EXT".."11",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_SINGLE_SUBPASS_EXT".."12",
        "SUBPASS_MERGE_STATUS_NOT_MERGED_UNSPECIFIED_EXT".."13"
    )
}