/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package vulkan.templates

import org.lwjgl.generator.*
import vulkan.*

val KHR_video_encode_quantization_map = "KHRVideoEncodeQuantizationMap".nativeClassVK("KHR_video_encode_quantization_map", type = "device", postfix = "KHR") {
    IntConstant(
        "KHR_VIDEO_ENCODE_QUANTIZATION_MAP_SPEC_VERSION".."2"
    )

    StringConstant(
        "KHR_VIDEO_ENCODE_QUANTIZATION_MAP_EXTENSION_NAME".."VK_KHR_video_encode_quantization_map"
    )

    EnumConstant(
        "STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_CAPABILITIES_KHR".."1000553000",
        "STRUCTURE_TYPE_VIDEO_FORMAT_QUANTIZATION_MAP_PROPERTIES_KHR".."1000553001",
        "STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_INFO_KHR".."1000553002",
        "STRUCTURE_TYPE_VIDEO_ENCODE_H264_QUANTIZATION_MAP_CAPABILITIES_KHR".."1000553003",
        "STRUCTURE_TYPE_VIDEO_ENCODE_H265_QUANTIZATION_MAP_CAPABILITIES_KHR".."1000553004",
        "STRUCTURE_TYPE_VIDEO_ENCODE_QUANTIZATION_MAP_SESSION_PARAMETERS_CREATE_INFO_KHR".."1000553005",
        "STRUCTURE_TYPE_VIDEO_FORMAT_H265_QUANTIZATION_MAP_PROPERTIES_KHR".."1000553006",
        "STRUCTURE_TYPE_VIDEO_ENCODE_AV1_QUANTIZATION_MAP_CAPABILITIES_KHR".."1000553007",
        "STRUCTURE_TYPE_VIDEO_FORMAT_AV1_QUANTIZATION_MAP_PROPERTIES_KHR".."1000553008",
        "STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_QUANTIZATION_MAP_FEATURES_KHR".."1000553009"
    )

    EnumConstant(
        "VIDEO_ENCODE_CAPABILITY_QUANTIZATION_DELTA_MAP_BIT_KHR".enum(0x00000004),
        "VIDEO_ENCODE_CAPABILITY_EMPHASIS_MAP_BIT_KHR".enum(0x00000008)
    )

    EnumConstant(
        "VIDEO_SESSION_CREATE_ALLOW_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR".enum(0x00000008),
        "VIDEO_SESSION_CREATE_ALLOW_ENCODE_EMPHASIS_MAP_BIT_KHR".enum(0x00000010)
    )

    EnumConstant(
        "VIDEO_SESSION_PARAMETERS_CREATE_QUANTIZATION_MAP_COMPATIBLE_BIT_KHR".enum(0x00000001)
    )

    EnumConstant(
        "VIDEO_ENCODE_WITH_QUANTIZATION_DELTA_MAP_BIT_KHR".enum(0x00000001),
        "VIDEO_ENCODE_WITH_EMPHASIS_MAP_BIT_KHR".enum(0x00000002)
    )

    EnumConstant(
        "IMAGE_USAGE_VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR".enum(0x02000000),
        "IMAGE_USAGE_VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR".enum(0x04000000)
    )

    EnumConstantLong(
        "FORMAT_FEATURE_2_VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR".enum(0x2000000000000L),
        "FORMAT_FEATURE_2_VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR".enum(0x4000000000000L)
    )

    EnumConstant(
        "IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR".."1000553000"
    )

    EnumConstant(
        "VIDEO_ENCODE_H264_CAPABILITY_MB_QP_DIFF_WRAPAROUND_BIT_KHR".enum(0x00000200)
    )

    EnumConstant(
        "VIDEO_ENCODE_H265_CAPABILITY_CU_QP_DIFF_WRAPAROUND_BIT_KHR".enum(0x00000400)
    )
}