/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package vulkan.templates

import org.lwjgl.generator.*
import vulkan.*

val KHR_video_encode_feedback2 = "KHRVideoEncodeFeedback2".nativeClassVK("KHR_video_encode_feedback2", type = "device", postfix = "KHR") {
    IntConstant(
        "KHR_VIDEO_ENCODE_FEEDBACK_2_SPEC_VERSION".."1"
    )

    StringConstant(
        "KHR_VIDEO_ENCODE_FEEDBACK_2_EXTENSION_NAME".."VK_KHR_video_encode_feedback2"
    )

    EnumConstant(
        "STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_FEEDBACK_2_FEATURES_KHR".."1000598000",
        "STRUCTURE_TYPE_VIDEO_ENCODE_FEEDBACK_2_CAPABILITIES_KHR".."1000598001",
        "STRUCTURE_TYPE_QUERY_POOL_VIDEO_ENCODE_PER_PARTITION_FEEDBACK_CREATE_INFO_KHR".."1000598002"
    )

    EnumConstant(
        "VIDEO_ENCODE_FEEDBACK_AVERAGE_QUANTIZATION_BIT_KHR".enum(0x00000008),
        "VIDEO_ENCODE_FEEDBACK_MIN_QUANTIZATION_BIT_KHR".enum(0x00000010),
        "VIDEO_ENCODE_FEEDBACK_MAX_QUANTIZATION_BIT_KHR".enum(0x00000020),
        "VIDEO_ENCODE_FEEDBACK_INTRA_PIXELS_BIT_KHR".enum(0x00000040),
        "VIDEO_ENCODE_FEEDBACK_INTER_PIXELS_BIT_KHR".enum(0x00000080),
        "VIDEO_ENCODE_FEEDBACK_SKIPPED_PIXELS_BIT_KHR".enum(0x00000100),
        "VIDEO_ENCODE_FEEDBACK_PICTURE_PARTITION_COUNT_BIT_KHR".enum(0x00000200)
    )

    EnumConstant(
        "VIDEO_ENCODE_PER_PARTITION_FEEDBACK_STATUS_BIT_KHR".enum(0x00000001),
        "VIDEO_ENCODE_PER_PARTITION_FEEDBACK_BITSTREAM_BUFFER_OFFSET_BIT_KHR".enum(0x00000002),
        "VIDEO_ENCODE_PER_PARTITION_FEEDBACK_BITSTREAM_BYTES_WRITTEN_BIT_KHR".enum(0x00000004)
    )
}