/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package vulkan.templates

import org.lwjgl.generator.*
import vulkan.*

val KHR_opacity_micromap = "KHROpacityMicromap".nativeClassVK("KHR_opacity_micromap", type = "device", postfix = "KHR") {
    IntConstant(
        "KHR_OPACITY_MICROMAP_SPEC_VERSION".."1"
    )

    StringConstant(
        "KHR_OPACITY_MICROMAP_EXTENSION_NAME".."VK_KHR_opacity_micromap"
    )

    EnumConstant(
        "STRUCTURE_TYPE_PHYSICAL_DEVICE_OPACITY_MICROMAP_FEATURES_KHR".."1000623000",
        "STRUCTURE_TYPE_PHYSICAL_DEVICE_OPACITY_MICROMAP_PROPERTIES_KHR".."1000623001",
        "STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_MICROMAP_DATA_KHR".."1000623002",
        "STRUCTURE_TYPE_ACCELERATION_STRUCTURE_TRIANGLES_OPACITY_MICROMAP_KHR".."1000623003"
    )

    EnumConstant(
        "PIPELINE_CREATE_RAY_TRACING_OPACITY_MICROMAP_BIT_KHR".enum(0x01000000)
    )

    EnumConstant(
        "GEOMETRY_INSTANCE_FORCE_OPACITY_MICROMAP_2_STATE_BIT_KHR".enum(0x00000010),
        "GEOMETRY_INSTANCE_DISABLE_OPACITY_MICROMAPS_BIT_KHR".enum(0x00000020)
    )

    EnumConstant(
        "BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_UPDATE_BIT_KHR".enum(0x00000040),
        "BUILD_ACCELERATION_STRUCTURE_ALLOW_DISABLE_OPACITY_MICROMAPS_BIT_KHR".enum(0x00000080),
        "BUILD_ACCELERATION_STRUCTURE_MICROMAP_LOSSY_BIT_KHR".enum(0x00000400)
    )

    EnumConstant(
        "ACCELERATION_STRUCTURE_TYPE_OPACITY_MICROMAP_KHR".."1000623000"
    )

    EnumConstant(
        "GEOMETRY_TYPE_MICROMAP_KHR".."1000623000"
    )

    EnumConstantLong(
        "PIPELINE_CREATE_2_RAY_TRACING_OPACITY_MICROMAP_BIT_KHR".enum(0x01000000L),
        "PIPELINE_CREATE_2_OPACITY_MICROMAP_DISALLOW_MIXED_SPECIAL_INDEX_BIT_KHR".enum(0x20000000000L)
    )

    EnumConstant(
        "SHADER_CREATE_OPACITY_MICROMAP_DISALLOW_MIXED_SPECIAL_INDEX_BIT_EXT".enum(0x00001000)
    )

    EnumConstant(
        "OPACITY_MICROMAP_FORMAT_2_STATE_KHR".."1",
        "OPACITY_MICROMAP_FORMAT_4_STATE_KHR".."2"
    )

    EnumConstant(
        "OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_TRANSPARENT_KHR".."-1",
        "OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_OPAQUE_KHR".."-2",
        "OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_TRANSPARENT_KHR".."-3",
        "OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_OPAQUE_KHR".."-4"
    )

    EnumConstant(
        "ACCELERATION_STRUCTURE_SERIALIZED_BLOCK_TYPE_OPACITY_MICROMAP_KHR".."0"
    )
}