/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package vulkan.templates

import org.lwjgl.generator.*
import vulkan.*

val KHR_video_decode_h264 = "KHRVideoDecodeH264".nativeClassVK("KHR_video_decode_h264", type = "device", postfix = "KHR") {
    IntConstant(
        "KHR_VIDEO_DECODE_H264_SPEC_VERSION".."9"
    )

    StringConstant(
        "KHR_VIDEO_DECODE_H264_EXTENSION_NAME".."VK_KHR_video_decode_h264"
    )

    EnumConstant(
        "STRUCTURE_TYPE_VIDEO_DECODE_H264_CAPABILITIES_KHR".."1000040000",
        "STRUCTURE_TYPE_VIDEO_DECODE_H264_PICTURE_INFO_KHR".."1000040001",
        "STRUCTURE_TYPE_VIDEO_DECODE_H264_PROFILE_INFO_KHR".."1000040003",
        "STRUCTURE_TYPE_VIDEO_DECODE_H264_SESSION_PARAMETERS_CREATE_INFO_KHR".."1000040004",
        "STRUCTURE_TYPE_VIDEO_DECODE_H264_SESSION_PARAMETERS_ADD_INFO_KHR".."1000040005",
        "STRUCTURE_TYPE_VIDEO_DECODE_H264_DPB_SLOT_INFO_KHR".."1000040006"
    )

    EnumConstant(
        "VIDEO_CODEC_OPERATION_DECODE_H264_BIT_KHR".enum(0x00000001)
    )

    EnumConstant(
        "VIDEO_DECODE_H264_PICTURE_LAYOUT_PROGRESSIVE_KHR".."0",
        "VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_INTERLEAVED_LINES_BIT_KHR".enum(0x00000001),
        "VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_SEPARATE_PLANES_BIT_KHR".enum(0x00000002)
    )
}