/*
 * Copyright LWJGL. All rights reserved.
 * License terms: https://www.lwjgl.org/license
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package vulkan.templates

import org.lwjgl.generator.*
import vulkan.*

val VALVE_video_encode_rgb_conversion = "VALVEVideoEncodeRgbConversion".nativeClassVK("VALVE_video_encode_rgb_conversion", type = "device", postfix = "VALVE") {
    IntConstant(
        "VALVE_VIDEO_ENCODE_RGB_CONVERSION_SPEC_VERSION".."1"
    )

    StringConstant(
        "VALVE_VIDEO_ENCODE_RGB_CONVERSION_EXTENSION_NAME".."VK_VALVE_video_encode_rgb_conversion"
    )

    EnumConstant(
        "STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_ENCODE_RGB_CONVERSION_FEATURES_VALVE".."1000390000",
        "STRUCTURE_TYPE_VIDEO_ENCODE_RGB_CONVERSION_CAPABILITIES_VALVE".."1000390001",
        "STRUCTURE_TYPE_VIDEO_ENCODE_PROFILE_RGB_CONVERSION_INFO_VALVE".."1000390002",
        "STRUCTURE_TYPE_VIDEO_ENCODE_SESSION_RGB_CONVERSION_CREATE_INFO_VALVE".."1000390003"
    )

    EnumConstant(
        "VIDEO_ENCODE_RGB_MODEL_CONVERSION_RGB_IDENTITY_BIT_VALVE".enum(0x00000001),
        "VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_IDENTITY_BIT_VALVE".enum(0x00000002),
        "VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_709_BIT_VALVE".enum(0x00000004),
        "VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_601_BIT_VALVE".enum(0x00000008),
        "VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_2020_BIT_VALVE".enum(0x00000010)
    )

    EnumConstant(
        "VIDEO_ENCODE_RGB_RANGE_COMPRESSION_FULL_RANGE_BIT_VALVE".enum(0x00000001),
        "VIDEO_ENCODE_RGB_RANGE_COMPRESSION_NARROW_RANGE_BIT_VALVE".enum(0x00000002)
    )

    EnumConstant(
        "VIDEO_ENCODE_RGB_CHROMA_OFFSET_COSITED_EVEN_BIT_VALVE".enum(0x00000001),
        "VIDEO_ENCODE_RGB_CHROMA_OFFSET_MIDPOINT_BIT_VALVE".enum(0x00000002)
    )
}